### PR TITLE
Refactored file structure and added exceptions to userService

### PR DESCRIPTION
**Pull request by JasonC01**

### CODE REVIEW

**Comment by senwei01** [comment]
Structuring the folder in this manner is sadly not adhering to microservices :( To make it a microservice implementation :

Each service should be in its own project ( in other words, when you run npm start on a service like userservice, it should only be users)

And it should be literally impossible for you to import anything from one microservice into another. Userservice should not be able to know what authservice does.

But yea whole philosophy of microservices is isolation, and also security in a way. Authservice implementation shud be secret and independent (i.e) auth service shud have its own database separate from userservice

**Comment by senwei01** [comment]
Just adding extra comments on how the backend microservices can be structured! Please correct me if im wrong or if you disagree haha.

Auth should be the only one public since its the source of truth. Everything else(every other services) should require an access token. The access token should come from only auth service's /oauth/token endpoint!

**Comment by senwei01** [comment]
https://stackoverflow.com/questions/65786135/nestjs-communication-between-2-microservice

In the case when two microservices have to interact, they shouldn't import each other directly, but communicate in this fashion. 

Or what I'm more familiar with is the http call way, which is also known as internal service calls. Not sure if this is the "NestJs" Way of doing things tho ahha. It basically is similar to the way we do calls with axios from frontend!

**Comment by senwei01** [comment]
Adding on to senwei's comment on decoupling auth from user, it's actually fine for user in userservice to reference user in authservice, they are completely different objects and tables

User service and auth service doesn't care about how each other implements User, nor how their tables are structured

User service just has to receive an "OK this user exists" or "No this user doesn't exist, pls delete it" from the auth service, that's the only dependency

**Comment by senwei01** [comment]
### From Ian

Making HTTP calls between microservices is actually quite common, perhaps more than the message queue pattern. It's the same as your Auth API making a call to Google's API if your user clicks "Log in with Google" for example.

**Review by rgonslayer — APPROVED** [review]
Refactoring seems to be well done, follows the Microservices architecture as we have agreed on.

Keep in mind that there is still a legacy backend folder which should not be used, otherwise this looks good to merge while we work on integrating the services.

**Pull request merged**
